# Generated by Django 5.1.5 on 2025-01-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GLOVO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
