# Generated by Django 5.1.5 on 2025-01-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GLOVO', '0002_contact_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingcourier',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
