# Generated by Django 5.1.5 on 2025-01-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GLOVO', '0003_alter_ratingcourier_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='courier',
        ),
        migrations.AlterField(
            model_name='courier',
            name='status',
            field=models.BooleanField(verbose_name='статус курьера'),
        ),
    ]
